name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8

    steps:
    - uses: actions/checkout@v3
    - name: Save BUILD_TAG
      run: |
        TIMESTAMP=`date +%Y%m%d%H%M%S`
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
        SNAPSHOT_TAG="${TIMESTAMP}-${SHORT_SHA}"
        ARCH=$(echo '${{ matrix.platform }}' | tr / _)
        echo "BUILD_TAG=$SNAPSHOT_TAG-$ARCH" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.REGISTRY }}
    - name: Build and Push setup
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        context: .
        platforms: ${{ matrix.platform }}
        tags: '${{ env.REGISTRY }}/agoric/instagoric-dashboard:${{ env.BUILD_TAG }}'
        push: true
        build-args: |
          TAG=${{ env.BUILD_TAG }}
